#include <stdio.h>
#include <string.h>

#include "man.h"

#ifndef SHYAKE_VERSION
#define SHYAKE_VERSION "dev"
#endif

struct man_entry {
	const char *name;
	const char *text;
};

static const struct man_entry man_table[] = {
	{ "init", "shyake init - Initialize\n\n"
		  "Usage:\n"
		  "    shyake init\n\n"
		  "    Generate config file and key pairs\n"
		  "    Default directory: ~/.config/shyake/\n\n"
		  "Options:\n"
		  "    -c <path>       Create multiple profiles at "
		  "alternative directories\n" },
	{ "register", "shyake register - Register on an instance\n\n"
		      "Notes: Run this after 'shyake init'\n\n"
		      "Usage:\n"
		      "    shyake register -u <username> -i <url>\n\n"
		      "Options:\n"
		      "    -u <username>   Your username\n"
		      "    -i <url>        Instance URL\n"
		      "    --debug         Output verbose curl logs to "
		      "stderr\n" },
	{ "send", "shyake send - Send a piece of mail\n\n"
		  "Usage:\n"
		  "    shyake send -t <username> [-s <subject>] [<file>]\n\n"
		  "    Read body from <file> or stdin.\n"
		  "    First line is used as subject if -s is omitted\n"
		  "    (subject must not exceed 128 bytes).\n\n"
		  "Options:\n"
		  "    -t <username>   To (required)\n"
		  "                    Use 'username@instance' for an "
		  "external recipient\n"
		  "    -s <subject>    Subject line\n"
		  "    -d, --draft <id>\n"
		  "                    Send a stored draft. Recipient and "
		  "subject\n"
		  "                    come from the draft unless -t/-s "
		  "override them.\n"
		  "                    The draft is deleted after a "
		  "successful send.\n"
		  "    --debug         Output verbose curl logs to "
		  "stderr\n\n"
		  "Note:\n"
		  "    shyake transmits text only. Binary data\n"
		  "    must be base64-encoded before sending.\n\n"
		  "Tips:\n"
		  "    Send a small image:\n"
		  "        base64 image.png | shyake send -t salmon -s "
		  "\"image.png\"\n"
		  "    Send a small archive:\n"
		  "        tar czf - ./source | base64 | shyake send -t "
		  "salmon -s \"source.tar.gz\"\n" },
	{ "check", "shyake check - Check inbox, sent, saved, or drafts\n\n"
		   "Usage:\n"
		   "    shyake check inbox|sent\n"
		   "    shyake check saved\n"
		   "    shyake check drafts\n"
		   "    shyake check <id>\n"
		   "    shyake check saved <id>\n"
		   "    shyake check drafts <id>\n\n"
		   "    'check inbox' and 'check sent' list mail from the "
		   "server.\n"
		   "    'check saved' lists locally saved mail.\n"
		   "    'check drafts' lists local encrypted drafts.\n"
		   "    'check <id>' shows the header of a single mail.\n"
		   "    'check saved <id>' shows the header of a locally "
		   "saved mail.\n"
		   "    'check drafts <id>' shows the header of a draft. "
		   "Use 'read drafts <id>' for full content.\n\n"
		   "Options:\n"
		   "    --count         Print count only\n"
		   "    --json          Output as JSON\n"
		   "    --csv           Output as CSV\n"
		   "    --no-header     Disable the column header\n"
		   "    --plain         Disable pager, color, and "
		   "truncation\n"
		   "    --no-color      Disable colored output\n"
		   "    --debug         Output verbose curl logs to "
		   "stderr\n" },
	{ "compose", "shyake compose - Compose or edit an encrypted "
		     "draft\n\n"
		     "Usage:\n"
		     "    shyake compose\n"
		     "    shyake compose <id>\n\n"
		     "    Opens your editor on a To/Subject/--- template "
		     "and stores\n"
		     "    the result as an encrypted draft in "
		     "~/.config/shyake/drafts/.\n"
		     "    Drafts are encrypted to your own key (ML-KEM-768 "
		     "+\n"
		     "    ChaCha20-Poly1305): saving needs no passphrase, "
		     "reading does.\n"
		     "    The 'To:' field may be left empty.\n"
		     "    'shyake compose <id>' edits an existing draft.\n\n"
		     "    Editor: EDITOR in config, else $VISUAL/$EDITOR, "
		     "else ed.\n"
		     "    vim/nvim run with -n -i NONE so no plaintext "
		     "touches swap files.\n\n"
		     "    Use 'shyake check drafts' to list drafts.\n"
		     "    Use 'shyake send --draft <id>' to send one.\n"
		     "    To delete a draft, remove its file from the "
		     "drafts directory.\n" },
	{ "fetch", "shyake fetch - Fetch and decrypt a piece of mail\n\n"
		   "Usage:\n"
		   "    shyake fetch <id>\n\n"
		   "Options:\n"
		   "    -r, --raw       Output body only (no header)\n"
		   "    --plain         Disable pager, color, and "
		   "truncation\n"
		   "    --no-color      Disable colored output\n"
		   "    --debug         Output verbose curl logs to "
		   "stderr\n\n"
		   "Tips:\n"
		   "    Save a piece of mail with header:\n"
		   "        shyake fetch <id> --no-color > output.txt\n"
		   "    Save a piece of mail (body only):\n"
		   "        shyake fetch <id> -r > output.txt\n"
		   "    Decode a received image:\n"
		   "        shyake fetch <id> -r | base64 -d > image.png\n"
		   "    Decode and extract a received archive:\n"
		   "        shyake fetch <id> -r | base64 -d | tar xzf -\n"
		   "    Extract into a specific directory:\n"
		   "        shyake fetch <id> -r | base64 -d | tar xzf - "
		   "-C ./output\n" },
	{ "burn", "shyake burn - Delete a piece of mail\n\n"
		  "Usage:\n"
		  "    shyake burn <id>\n\n"
		  "Options:\n"
		  "    --debug         Output verbose curl logs to "
		  "stderr\n" },
	{ "block", "shyake block - Block a user or instance\n\n"
		   "Usage:\n"
		   "    shyake block <target>\n\n"
		   "    <target> can be a username or an instance URL.\n\n"
		   "Options:\n"
		   "    --debug         Output verbose curl logs to "
		   "stderr\n" },
	{ "unblock", "shyake unblock - Unblock a user or instance\n\n"
		     "Usage:\n"
		     "    shyake unblock <target>\n\n"
		     "    <target> can be a username or an instance "
		     "URL.\n\n"
		     "Options:\n"
		     "    --debug         Output verbose curl logs to "
		     "stderr\n" },
	{ "blocklist", "shyake blocklist - List blocked users and "
		       "instances\n\n"
		       "Usage:\n"
		       "    shyake blocklist\n\n"
		       "    Prints every target you have blocked, newest "
		       "first.\n\n"
		       "Options:\n"
		       "    --debug         Output verbose curl logs to "
		       "stderr\n" },
	{ "rotate", "shyake rotate - Rotate key pairs\n\n"
		    "Usage:\n"
		    "    shyake rotate\n\n"
		    "    Regenerates your key pairs and clears all mail "
		    "to and from you.\n\n"
		    "Options:\n"
		    "    --debug         Output verbose curl logs to "
		    "stderr\n" },
	{ "fingerprint", "shyake fingerprint - Show or update "
			 "fingerprint\n\n"
			 "Usage:\n"
			 "    shyake fingerprint\n"
			 "    shyake fingerprint <username>\n"
			 "    shyake fingerprint <username> --update\n\n"
			 "    Without argument: show your own "
			 "fingerprint.\n"
			 "    With <username>: fetch and display their "
			 "public key.\n"
			 "    --update: refresh the stored key for "
			 "<username>.\n"
			 "    Verify the new fingerprint out-of-band before "
			 "running\n"
			 "    --update to prevent identity impersonation.\n\n"
			 "Options:\n"
			 "    --update        Update stored key for "
			 "<username>\n"
			 "    --debug         Output verbose curl logs to "
			 "stderr\n" },
	{ "whoami", "shyake whoami - Show current identity\n\n"
		    "Usage:\n"
		    "    shyake whoami\n\n"
		    "    Displays USERNAME, INSTANCE, and CONFIG "
		    "directory.\n" },
	{ "destroy", "shyake destroy - Destroy identity\n\n"
		     "Usage:\n"
		     "    shyake destroy\n\n"
		     "    Deletes local config and key pairs, destructs "
		     "the account\n"
		     "    on the instance. All mail is cleared. The "
		     "username is\n"
		     "    permanently locked on this instance.\n\n"
		     "Options:\n"
		     "    --debug         Output verbose curl logs to "
		     "stderr\n" },
	{ "version", "shyake version - Show client version\n\n"
		     "Usage:\n"
		     "    shyake version\n" },
	{ "save", "shyake save - Save a piece of mail locally\n\n"
		  "Usage:\n"
		  "    shyake save <id>\n\n"
		  "    Fetches the encrypted mail from the server\n"
		  "    and stores it to ~/.config/shyake/saved/<id>.json.\n"
		  "    The mail is NOT decrypted at this stage.\n"
		  "    Use 'shyake check saved' to list saved mail.\n"
		  "    Use 'shyake read <id>' to decrypt and display.\n\n"
		  "Options:\n"
		  "    --debug         Output verbose curl logs to "
		  "stderr\n" },
	{ "read", "shyake read - Read a locally saved mail or draft\n\n"
		  "Usage:\n"
		  "    shyake read <id>\n"
		  "    shyake read drafts <id>\n\n"
		  "    'read <id>' decrypts and displays a mail saved by "
		  "'shyake save'.\n"
		  "    'read drafts <id>' decrypts and displays a local "
		  "draft in full.\n"
		  "    Output is identical to 'shyake fetch'.\n\n"
		  "Options:\n"
		  "    -r, --raw       Output body only (no header)\n"
		  "    --no-color      Disable colored output\n" },
	{ "enc", "shyake enc - Encrypt a file\n\n"
		 "Usage:\n"
		 "    shyake enc <file> [-t <username>] [-o <output>]\n\n"
		 "    Encrypts <file> using ML-KEM-768 + "
		 "ChaCha20-Poly1305.\n"
		 "    Without -t: uses your own public key.\n"
		 "    With -t: fetches and uses the recipient's public "
		 "key.\n"
		 "    Output defaults to <file>.enc\n\n"
		 "Options:\n"
		 "    -t <username>   Encrypt for a recipient\n"
		 "    -o <path>       Output file path\n"
		 "    --debug         Output verbose curl logs to "
		 "stderr\n\n"
		 "Note: This command is intended for debugging/testing "
		 "purposes.\n" },
	{ "dec", "shyake dec - Decrypt a file\n\n"
		 "Usage:\n"
		 "    shyake dec <file> [-o <output>]\n\n"
		 "    Decrypts a .enc file using your KEM secret key.\n"
		 "    Without -o: writes decrypted bytes to stdout.\n\n"
		 "Options:\n"
		 "    -o <path>       Output file path\n\n"
		 "Note: This command is intended for debugging/testing "
		 "purposes.\n" },
	{ "update", "shyake update - Check and install updates\n\n"
		    "Usage:\n"
		    "    shyake update\n"
		    "    shyake update stable\n"
		    "    shyake update preview\n\n"
		    "    'shyake update' shows installed and available "
		    "versions.\n"
		    "    'shyake update stable' installs the latest stable "
		    "release.\n"
		    "    'shyake update preview' installs the latest "
		    "preview release.\n"
		    "    Preview is only offered when newer than "
		    "stable.\n" },
	{ "man", "shyake man - Show manual pages\n\n"
		 "Usage:\n"
		 "    shyake man\n"
		 "    shyake man <command>\n" },
};

#define MAN_TABLE_LEN (sizeof(man_table) / sizeof(man_table[0]))

void cli_print_man(const char *subcmd)
{
	size_t i;

	if (!subcmd) {
		printf("Usage: shyake [option] [command]\n\n"
		       "shyake %s - PQC E2EE mailer\n\n"
		       "Commands:\n"
		       "  init          Initialize\n"
		       "  register      Register on an instance\n"
		       "  send          Send a piece of mail\n"
		       "  compose       Compose or edit an encrypted "
		       "draft\n"
		       "  check         Check inbox, sent, saved, or "
		       "drafts\n"
		       "  fetch         Fetch and decrypt a piece of "
		       "mail\n"
		       "  save          Save a piece of mail locally\n"
		       "  read          Read a locally saved mail\n"
		       "  burn          Burn a piece of mail\n"
		       "  block         Block a user or instance\n"
		       "  unblock       Unblock a user or instance\n"
		       "  blocklist     List blocked users and "
		       "instances\n"
		       "  rotate        Rotate key pairs\n"
		       "  fingerprint   Show or update fingerprint\n"
		       "  whoami        Show current identity\n"
		       "  destroy       Destroy identity\n"
		       "  enc           Encrypt a file\n"
		       "  dec           Decrypt a file\n"
		       "  update        Check and install updates\n"
		       "  man           Show manual pages\n"
		       "  version       Show client version\n\n"
		       "Global Options:\n"
		       "  -c, --config  Use an alternative config "
		       "directory\n"
		       "  --plain       Disable pager, color, and "
		       "truncation\n"
		       "  --no-color    Disable colored output\n"
		       "  --debug       Output verbose curl logs to "
		       "stderr\n\n"
		       "For detailed usage, run: shyake man <command>\n\n"
		       "Copyright (c) 2026 Salmonization. Released under "
		       "the BSD 2-Clause License.\n"
		       "Source, issues, and contributions: "
		       "https://github.com/salmonization/shyake\n",
		       SHYAKE_VERSION);
		return;
	}

	for (i = 0; i < MAN_TABLE_LEN; i++) {
		if (strcmp(subcmd, man_table[i].name) == 0) {
			fputs(man_table[i].text, stdout);
			return;
		}
	}

	printf("Unknown command: %s\n", subcmd);
	printf("Run 'shyake man' for a list of available commands.\n");
}
